server:
  port: 9078    #port number
 
spring:
  application:
    name: school-service    #service name
    
rbc:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8098,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000